### ISSUE TITLE
Confirm location-uuid should be nullable

### ISSUE THREAD

**Issue by batkinson** [cims-bioko/cims-server#114]
After experiencing errors caused by null location_uuid fields for social groups in the tablet application, it makes sense to confirm that allowing a null for location_uuid is correct. Depending on the result, it may make sense to relax the constraint on the tablet or enforce it on the server.

**Comment by bruceMacLeod** [comment]
The OpenHDS model does not have location associated with a social group. If social groups model a family and all family members are in the same place, then you can get the current residency of the HOH to find the location of the family. Detaching location from the family allows for modeling families that may stretch across multiple locations. It also makes moving family members easier. 

For Bioko, social groups and locations are one & the same (at least for now) and I suspect there is little interest in modeling families across multiple locations.  At some point though, we will need to model families moving and, if the location id is not tied up with the social group, we can model that transition as a change in residency for all family members.  So I do not understand why a location id is attached to the social group.

**Comment by batkinson** [comment]
Ok, that makes sense. In this case, it makes sense to look at the linkage in the tablet app and see if the constraint is actually necessary. I suspect it may actually be an artificial constraint caused by wanting to unify everything under DataWrapper. If that's the case, I may just see what's involved in moving to another scheme - I'm not a fan of the design due to it over-constraining the domain classes via inheritance.
