### ISSUE TITLE
Mirth uses string "null" in place of NULL values

### ISSUE THREAD

**Issue by benjamin-heasly** [cims-bioko/cims-server#42]
Mirth converts rows from the ODK Aggregate database to XML documents.  Currently, where the database contains NULL values, Mirth writes the string "null" in the XML documents.

"null" strings may be misinterpreted in objects unmarshalled from the XML documents because "null" is a string, not a NULL value.

Instead, Mirth should leave empty tags in place of NULL values.  This will allow XML documents to be unmarshalled and retain NULL values where they belong.

**Comment by batkinson** [comment]
This issue is actually not related to the cims-server project (openhds). It is an issue with the mirth channel script we developed.

**Comment by batkinson** [comment]
Ben's comment above "Instead, Mirth should leave empty tags in place of NULL values." is incorrect. The way this should be handled is:

- Non-null values should be added as elements (including empty string, which is represented as an empty element)
- Undefined values or values that are null should not contribute an element to the document

The key distinction here is described by the following analogy:

Lack of an element is to an empty element as an undefined String value is to the empty String

**Comment by batkinson** [comment]
This was fixed in cims-server/mirth-channels@d9053108bfd932

**Comment by batkinson** [comment]
The xml generation function was updated in production by importing the updated code-template xml document and redeploying the channels.
